---
- name: Import precheck tasks
  ansible.builtin.import_tasks: precheck.yml
  tags: precheck

- name: Import prepare tasks
  ansible.builtin.import_tasks: prepare.yml

- name: Import confirmation tasks
  ansible.builtin.import_tasks: confirm_swap.yml

- name: Import swap tasks
  ansible.builtin.import_tasks: swap.yml

- name: Import verify tasks
  ansible.builtin.import_tasks: verify.yml

- name: Import deprovision tasks if requested
  ansible.builtin.import_tasks: deprovision_source_host.yml
  when: deprovision_source_host | default(false) | bool

- name: Import summary tasks
  ansible.builtin.import_tasks: summary.yml
