# Validator configuration defaults
solana_user: sol
validator_service: sol.service
validator_log_file: /home/{{ solana_user }}/logs/agave-validator.log
validator_log_dir: /home/{{ solana_user }}/logs
validator_config_dir: /home/{{ solana_user }}/.solana
validator_ledger_dir: /mnt/ledger
validator_accounts_dir: /mnt/accounts
validator_snapshots_dir: /mnt/snapshots
