services:
  gossip-entrypoint:
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw

  host-alpha:
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /mnt/ledger
      - /mnt/accounts
      - /mnt/snapshots
      - ./container-setup/scripts/set-container-default-user-ssh-key.sh:/container-setup/scripts/set-container-default-user-ssh-key.sh
      - ./container-setup/scripts/set-validator-service-user-ssh-key.sh:/container-setup/scripts/set-validator-service-user-ssh-key.sh
      - ./localnet-ssh-keys:/localnet-ssh-keys

  host-bravo:
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /mnt/ledger
      - /mnt/accounts
      - /mnt/snapshots
      - ./container-setup/scripts/set-container-default-user-ssh-key.sh:/container-setup/scripts/set-container-default-user-ssh-key.sh
      - ./container-setup/scripts/set-validator-service-user-ssh-key.sh:/container-setup/scripts/set-validator-service-user-ssh-key.sh
      - ./localnet-ssh-keys:/localnet-ssh-keys

  host-charlie:
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - ./container-setup/scripts/set-container-default-user-ssh-key.sh:/container-setup/scripts/set-container-default-user-ssh-key.sh
      - ./localnet-ssh-keys:/localnet-ssh-keys
