services:
  gossip-entrypoint:
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw

  host-alpha:
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw

  host-bravo:
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw

  host-charlie:
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw

  host-monitoring:
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
