---
# Grafana datasource configuration tasks (after InfluxDB setup)

- name: Configure Grafana datasource provisioning
  ansible.builtin.template:
    src: grafana/datasources.yml.j2
    dest: "{{ grafana_config.provisioning_dir }}/datasources/datasources.yml"
    owner: "{{ grafana_config.permissions.config_files.owner }}"
    group: "{{ grafana_config.permissions.config_files.group }}"
    mode: "{{ grafana_config.permissions.config_files.mode }}"
  notify: restart grafana
  when: hardware_metrics_token is defined and solana_metrics_token is defined