---
# Install Telegraf on Ubuntu
- name: Add InfluxData APT repository
  ansible.builtin.apt_repository:
    repo: 'deb https://repos.influxdata.com/ubuntu {{ ansible_distribution_release }} stable'
    state: present
    filename: 'influxdata'

- name: Add InfluxData GPG key
  ansible.builtin.apt_key:
    url: 'https://repos.influxdata.com/influxdb.key'
    state: present

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install telegraf
  ansible.builtin.apt:
    name: telegraf
    state: present
