---
# Main Telegraf tasks orchestrator

- name: Include Telegraf installation tasks
  include_tasks: telegraf/install.yml

- name: Include Telegraf configuration tasks
  include_tasks: telegraf/configure.yml