---
# Main Telegraf tasks orchestrator

- name: Include Telegraf installation tasks
  include_tasks: telegraf/install.yml

- name: Include Telegraf configuration tasks
  include_tasks: telegraf/configure.yml

# Si tienes servicios separados, puedes incluirlos aqu√≠
# - name: Include Telegraf service management tasks
#   include_tasks: telegraf/services.yml