solana_user: "{{ lookup('ansible.builtin.pipe', 'id -u sol > /dev/null 2>&1 && echo sol || echo ' + ansible_facts['user_id']) }}"
solana_cli_bin_path: "$HOME/.local/share/solana/install/active_release/bin"
solana_channel: "stable"
