---
source_host_keys_dir: "{{ validator_keys_dir }}/{{ source_validator_name }}"
source_host_identity_link_path: "{{ source_host_keys_dir }}/identity.json"
source_vote_account_path: "{{ source_host_keys_dir }}/vote-account.json"
destination_host_keys_dir: "{{ validator_keys_dir }}/{{ destination_validator_name }}"
destination_host_identity_link_path: "{{ destination_host_keys_dir }}/identity.json"
source_host_address: "{{ hostvars[source_host]['ansible_host'] | default(hostvars[source_host]['inventory_hostname'] | default(source_host)) }}"
destination_host_address: "{{ hostvars[destination_host]['ansible_host'] | default(hostvars[destination_host]['inventory_hostname'] | default(destination_host)) }}"
destination_host_port: "{{ hostvars[destination_host]['ansible_port'] | default(22) }}"
