---
# SSL / Certbot configuration tasks

- name: Include Certbot installation tasks
  include_tasks: ssl_certificates/install.yml

- name: Include Certbot configuration and certificate issuance tasks
  include_tasks: ssl_certificates/configure.yml
