---
# Solana Localnet-specific, non-secret (rare) variables
solana_rpc_url: http://gossip-entrypoint:8899
jito_bam_endpoints:
  dallas:
    bam_url: "http://dallas.testnet.bam.jito.wtf"
    block_engine_url: "https://dallas.testnet.block-engine.jito.wtf"
    shred_receiver_addr: "141.98.218.12:1002"
    ntp_server: "ntp.dallas.jito.wtf"
  newyork:
    bam_url: "http://ny.testnet.bam.jito.wtf"
    block_engine_url: "https://ny.testnet.block-engine.jito.wtf"
    shred_receiver_addr: "64.130.35.224:1002"
    ntp_server: "ntp.dallas.jito.wtf"

expected_genesis_hash: ""
solana_metrics_url: ""
# Keep ledger size bounded (value is in shreds, ~62.5 GB target)
limit_ledger_size: 50000000
poh_pinned_cpu_core_enabled: false
poh_pinned_cpu_core: 2

# Maximum percentage of network delinquent stake allowed before validator can restart
restart_max_delinquent_stake: 20
# Minimum time (in seconds) validator must be idle before allowing restart (0 = no delay)
restart_min_idle_time: 0

# Maximum percentage of credits loss allowed for automatic deprovisioning of source host
credits_loss_threshold: 6

solana_gossip_entrypoints:
  - gossip-entrypoint:8001

known_validators: []

jito_tip_payment_program_pubkey: "GJHtFqM9agxPmkeKjHny6qiRKrXZALvvFGiKf11QE7hy"
jito_tip_distribution_program_pubkey: "DzvGET57TAgEDxvm3ERUM4GNcsAJdqjDLCne9sdfY4wf"
jito_merkle_root_upload_authority: "7T4inmPmtNBX3MhLwJ9hFsSMnGJYYkKioVABSNTWVRuS"
jito_commission_bps: 0
