---
# Solana Testnet-specific, non-secret (rare) variables
solana_rpc_url: https://api.testnet.solana.com
jito_bam_endpoints:
  dallas:
    bam_url: "http://dallas.testnet.bam.jito.wtf"
    block_engine_url: "https://dallas.testnet.block-engine.jito.wtf"
    shred_receiver_addr: "141.98.218.12:1002"
    ntp_server: "ntp.dallas.jito.wtf"
  newyork:
    bam_url: "http://ny.testnet.bam.jito.wtf"
    block_engine_url: "https://ny.testnet.block-engine.jito.wtf"
    shred_receiver_addr: "64.130.35.224:1002"
    ntp_server: "ntp.dallas.jito.wtf"

expected_genesis_hash: '4uhcVJyU9pJkvQyS88uRDiswHXSCkY3zQawwpjk2NsNY'
solana_metrics_url: 'https://metrics.solana.com:8086,db=tds,u=testnet_write,p=c4fa841aa918bf8274e3e2a44d77568d9861b3ea'
# Keep ledger size bounded (value is in shreds, ~200 GB target)
limit_ledger_size: 160000000

poh_pinned_cpu_core_enabled: true
poh_pinned_cpu_core: 2

# Maximum percentage of network delinquent stake allowed before validator can restart
restart_max_delinquent_stake: 10
# Minimum time (in seconds) validator must be idle before allowing restart (0 = no delay)
restart_min_idle_time: 5

# Maximum percentage of credits loss allowed for automatic deprovisioning of source host
credits_loss_threshold: 4

solana_gossip_entrypoints:
  - entrypoint.testnet.solana.com:8001
  - entrypoint2.testnet.solana.com:8001
  - entrypoint3.testnet.solana.com:8001

known_validators:
  - 5D1fNXzvv5NjV1ysLjirC4WY92RNsVH18vjmcszZd8on
  - dDzy5SR3AXdYWVqbDEkVFdvSPCtS9ihF5kJkHCtXoFs
  - Ft5fbkqNa76vnsjYNwjDZUXoTWpP7VYm3mtsaQckQADN
  - eoKpUABi59aT4rR9HGS3LcMecfut9x7zJyodWWP43YQ
  - 9QxCLckBiJc783jnMvXZubK4wH86Eqqvashtrwvcsgkv

jito_tip_payment_program_pubkey: "GJHtFqM9agxPmkeKjHny6qiRKrXZALvvFGiKf11QE7hy"
jito_tip_distribution_program_pubkey: "DzvGET57TAgEDxvm3ERUM4GNcsAJdqjDLCne9sdfY4wf"
jito_merkle_root_upload_authority: "7T4inmPmtNBX3MhLwJ9hFsSMnGJYYkKioVABSNTWVRuS"
jito_commission_bps: 0
