---
# Solana Mainnet-specific, non-secret (rare) variables
solana_rpc_url: https://api.mainnet-beta.solana.com
jito_bam_endpoints:
  amsterdam:
    bam_url: "http://amsterdam.mainnet.bam.jito.wtf"
    block_engine_url: "https://amsterdam.mainnet.block-engine.jito.wtf"
    shred_receiver_addr: "74.118.140.240:1002"
    ntp_server: "ntp.amsterdam.jito.wtf"
  frankfurt:
    bam_url: "http://frankfurt.mainnet.bam.jito.wtf"
    block_engine_url: "https://frankfurt.mainnet.block-engine.jito.wtf"
    shred_receiver_addr: "64.130.50.14:1002"
    ntp_server: "ntp.frankfurt.jito.wtf"
  london:
    bam_url: "http://london.mainnet.bam.jito.wtf"
    block_engine_url: "https://london.mainnet.block-engine.jito.wtf"
    shred_receiver_addr: "142.91.127.175:1002"
    ntp_server: "ntp.london.jito.wtf"
  newyork:
    bam_url: "http://ny.mainnet.bam.jito.wtf"
    block_engine_url: "https://ny.mainnet.block-engine.jito.wtf"
    shred_receiver_addr: "141.98.216.96:1002"
    ntp_server: "ntp.dallas.jito.wtf"
  salt_lake_city:
    bam_url: "http://slc.mainnet.bam.jito.wtf"
    block_engine_url: "https://slc.mainnet.block-engine.jito.wtf"
    shred_receiver_addr: "64.130.53.8:1002"
    ntp_server: "ntp.slc.jito.wtf"
  singapore:
    bam_url: "http://singapore.mainnet.bam.jito.wtf"
    block_engine_url: "https://singapore.mainnet.block-engine.jito.wtf"
    shred_receiver_addr: "202.8.11.224:1002"
    ntp_server: "ntp.singapore.jito.wtf"
  tokyo:
    bam_url: "http://tokyo.mainnet.bam.jito.wtf"
    block_engine_url: "https://tokyo.mainnet.block-engine.jito.wtf"
    shred_receiver_addr: "202.8.9.160:1002"
    ntp_server: "ntp.tokyo.jito.wtf"

expected_genesis_hash: '5eykt4UsFv8P8NJdTREpY1vzqKqZKvdpKuc147dw2N9d'
solana_metrics_url: 'https://metrics.solana.com:8086,db=mainnet-beta,u=mainnet-beta_write,p=password'

# Not specifying a value for limit_ledger_size will use the default ~500GB.

poh_pinned_cpu_core_enabled: true
poh_pinned_cpu_core: 2

# Maximum percentage of network delinquent stake allowed before validator can restart
restart_max_delinquent_stake: 5
# Minimum time (in seconds) validator must be idle before allowing restart (0 = no delay)
restart_min_idle_time: 30

# Maximum percentage of credits loss allowed for automatic deprovisioning of source host
credits_loss_threshold: 2

solana_gossip_entrypoints:
  - entrypoint.mainnet-beta.solana.com:8001
  - entrypoint2.mainnet-beta.solana.com:8001
  - entrypoint3.mainnet-beta.solana.com:8001
  - entrypoint4.mainnet-beta.solana.com:8001
  - entrypoint5.mainnet-beta.solana.com:8001

known_validators:
  - 7Np41oeYqPefeNQEHSv1UDhYrehxin3NStELsSKCT4K2
  - GdnSyH3YtwcxFvQrVVJMm1JhTS4QVX7MFsX56uJLUfiZ
  - DE1bawNcRJB9rVm3buyMVfr8mBEoyyu73NBovf2oXJsJ
  - CakcnaRDHka2gXyfbEd2d3xsvkJkqsLw2akB3zsN1D2S

jito_tip_payment_program_pubkey: "T1pyyaTNZsKv2WcRAB8oVnk93mLJw2XzjtVYqCsaHqt"
jito_tip_distribution_program_pubkey: "4R3gSG8BpU4t19KYj8CfnbtRpnT8gtk4dvTHxVRwc2r7"
jito_merkle_root_upload_authority: "8F4jGUmxF36vQ6yabnsxX6AQVXdKBhs8kGSUuRKSg8Xt"
jito_commission_bps: 0
