---
# Render Validator Metrics Environment file
- name: Render Validator Metrics Environment file
  ansible.builtin.template:
    src: validator_metrics_service/validator-metrics.env.j2
    dest: "/etc/validator-metrics/validator-metrics.env"
    owner: root
    group: root
    mode: '0600'