---
jito_relayer_install_dir: "{{ solana_user_dir }}/.local/share/jito-relayer/install/active_release"
ansible_keys_dir: "{{ ansible_home_dir }}/.validator-keys/{{ validator_keyset_name | default(validator_name) }}"
validator_keyset_dir: "{{ keys_dir }}/{{ validator_name }}"
default_group: "{{ solana_user | default('') }}"
default_file_mode: "0600"
default_directory_mode: "0755"
