---
dependencies:
  - role: rust_env_v2
  - role: solana_cli_jito
    vars:
      agave_version: "{{ jito_version }}"
  - role: solana_validator_shared
    vars:
      validator_name: "{{ validator_name }}"
