---
# Override the default validator directories with V2 values
jito_min_bam_version: "3.0.10"
keys_dir: "{{ validator_keys_dir }}"
default_group: "{{ validator_operators_group }}"
default_file_mode: "{{ validator_key_file_mode }}"
default_directory_mode: "{{ validator_data_mode_owner_readonly }}"
