---
all:
  hosts:
    host-alpha:
      ansible_host: 172.25.0.11
      ansible_port: 22
    host-bravo:
      ansible_host: 172.25.0.12
      ansible_port: 22
    host-charlie:
      ansible_host: 172.25.0.13
      ansible_port: 22

  children:
    # ───── City Grouping ─────
    city_dal:
      hosts:
        host-alpha:
        host-bravo:
        host-charlie:

    # ───── Network Grouping ─────
    solana:
      hosts:
        host-alpha:
        host-bravo:
        host-charlie:

    # ───── Solana Cluster Grouping ─────
    solana_localnet:
      hosts:
        host-alpha:
        host-bravo:
        host-charlie: