---
- name: Get Agave Download URL
  ansible.builtin.shell: |
    set -e
    echo "{{ official_agave_repo }}/releases/download/v{{ agave_version }}/solana-release-{{ host_arch }}.tar.bz2"
  args:
    executable: /bin/bash
  register: agave_download_url_reg
  changed_when: false

- name: Set Solana Agave download URL as a fact
  ansible.builtin.set_fact:
    agave_download_url: "{{ agave_download_url_reg.stdout }}"

- name: Print the Agave download URL
  ansible.builtin.debug:
    msg: "Solana CLI will be downloaded from: {{ agave_download_url }}"

- name: Create Solana CLI releases directory
  ansible.builtin.file:
    path: "{{ solana_installed_releases_dir }}/v{{ agave_version }}"
    state: directory
    mode: '0755'

- name: Unarchiving solana binaries into the releases directory
  ansible.builtin.debug:
    msg: "Unarchive release directory: {{ solana_installed_releases_dir }}/v{{ agave_version }}"

- name: Unarchive solana binaries
  ansible.builtin.unarchive:
    src: "{{ agave_download_url }}"
    dest: "{{ solana_installed_releases_dir }}/v{{ agave_version }}"
    remote_src: true
    creates: "{{ solana_installed_releases_dir }}/v{{ agave_version }}/solana-release/bin/agave-validator"
  ignore_errors: "{{ ansible_check_mode }}" # can be also: when: not ansible_check_mode

- name: Create symlink to new release
  ansible.builtin.file:
    src: "{{ solana_installed_releases_dir }}/v{{ agave_version }}/solana-release"
    dest: "{{ solana_user_dir }}/.local/share/solana/install/active_release"
    state: link
    force: true
