---
# Monitoring Agent Variables
monitoring_hub:
  host: "{{ monitoring_hub_host }}"
  port: 8086
  org: "{{ influxdb_init_org }}"
  hardware_bucket: "{{ hardware_bucket_name }}"
  hardware_bucket_token: "{{ influxdb_hardware_bucket_token }}"