---
- name: handlers - Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: handlers - Restart relayer service
  ansible.builtin.systemd:
    name: "{{ jito_relayer_service_name }}"
    state: restarted
  become: true

- name: handlers - Restart validator service
  ansible.builtin.systemd:
    name: "{{ validator_service_name }}"
    state: restarted
  become: true

- name: handlers - Restart validator logrotate timer
  ansible.builtin.systemd:
    name: "validator-logrotate-{{ validator_service_name }}.timer"
    state: restarted
  become: true
  when: solana_cluster == 'localnet'
