---
- name: handlers - Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: handlers - Restart relayer service
  ansible.builtin.systemd:
    name: "{{ jito_relayer_service_name }}"
    state: restarted
  become: true
